services:
  docs:
    image: wonderland_local_docs
    container_name: wonderland_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
    ports:
      - '9000:9000'
    command: /start-docs
